QUALITY_LOW_A = 0
QUALITY_LOW_B = 0
QUALITY_LOW_C = 20
QUALITY_LOW_D = 40

QUALITY_MEDIUM_A = 20
QUALITY_MEDIUM_B = 40
QUALITY_MEDIUM_C = 80
QUALITY_MEDIUM_D = 95

QUALITY_HIGH_A = 80
QUALITY_HIGH_B = 95
QUALITY_HIGH_C = 100
QUALITY_HIGH_D = 100

PRICE_CHEAP_A = 0
PRICE_CHEAP_B = 0
PRICE_CHEAP_C = 3
PRICE_CHEAP_D = 5

PRICE_MEDIUM_A = 3
PRICE_MEDIUM_B = 5
PRICE_MEDIUM_C = 9

PRICE_EXPENSIVE_A = 5
PRICE_EXPENSIVE_B = 9
PRICE_EXPENSIVE_C = 10
PRICE_EXPENSIVE_D = 10

WORTHINESS_BAD_A = 0
WORTHINESS_BAD_B = 0
WORTHINESS_BAD_C = 50
WORTHINESS_BAD_D = 70

WORTHINESS_GOOD_A = 50
WORTHINESS_GOOD_B = 70
WORTHINESS_GOOD_C = 80
WORTHINESS_GOOD_D = 90

WORTHINESS_EXCELLENT_A = 80
WORTHINESS_EXCELLENT_B = 90
WORTHINESS_EXCELLENT_C = 100
WORTHINESS_EXCELLENT_D = 100
